name: Build Core (no MAUI)

on:
  push: { branches: ["**"] }
  pull_request: { branches: ["**"] }
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      # Bouw alleen de core-projecten, dwing net8.0 af en negeer MAUI/iOS
      - name: Restore Grocery.Core
        run: dotnet restore "./Grocery.Core/Grocery.Core.csproj" -p:TargetFramework=net8.0

      - name: Build Grocery.Core
        run: dotnet build "./Grocery.Core/Grocery.Core.csproj" -c Release -p:TargetFramework=net8.0 --no-restore

      - name: Restore Grocery.Core.Data
        run: dotnet restore "./Grocery.Core.Data/Grocery.Core.Data.csproj" -p:TargetFramework=net8.0

      - name: Build Grocery.Core.Data
        run: dotnet build "./Grocery.Core.Data/Grocery.Core.Data.csproj" -c Release -p:TargetFramework=net8.0 --no-restore
